export { HERO_CONTENT } from "./hero.js";
export { NAV_LINKS } from "./nav.js";
export { SKILLS, SKILLS_CATEGORIES } from "./skills.js";
export { PROJECTS, PROJECT_CATEGORIES } from "./projects.js";
export { EXPERIENCE } from "./experience.js";
export { INTERNSHIPS } from "./internships.js";
export { CERTIFICATES } from "./certificates.js";
export { TESTIMONIALS } from "./testimonials.js";
export { CONTACT } from "./contact.js";
export { STATS } from "./stats.js";
export { ABOUT_CARDS } from "./about.js";